In [2]:
import pandas as pd
dataset = pd.read_csv('C:\\Users\\Enass Irfan\\Downloads\\IMDB Dataset.csv')
dataset

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [3]:
#replace data
# positive 1
# negative 0
dataset.replace({'sentiment': {'positive': 1, "negative" : 0}}, inplace= True)
dataset

                                                  review  sentiment
0      One of the other reviewers has mentioned that ...          1
1      A wonderful little production. <br /><br />The...          1
2      I thought this was a wonderful way to spend ti...          1
3      Basically there's a family where a little boy ...          0
4      Petter Mattei's "Love in the Time of Money" is...          1
...                                                  ...        ...
49995  I thought this movie did a down right good job...          1
49996  Bad plot, bad dialogue, bad acting, idiotic di...          0
49997  I am a Catholic taught in parochial elementary...          0
49998  I'm going to have to disagree with the previou...          0
49999  No one expects the Star Trek movies to be high...          0

[50000 rows x 2 columns]

In [8]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to C:\Users\Enass
[nltk_data]     Irfan\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to C:\Users\Enass
[nltk_data]     Irfan\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to C:\Users\Enass
[nltk_data]     Irfan\AppData\Roaming\nltk_data...
[nltk_data] Downloading package omw-1.4 to C:\Users\Enass
[nltk_data]     Irfan\AppData\Roaming\nltk_data...

True

#  Text Preprocessing

In [13]:
# import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
stopWords = set(stopwords.words('english'))

def preprocessing(text):
    #tokenization
    tokens = nltk.word_tokenize(text.lower())
    #removing of stopwords
    tokens = [lemmatizer.lemmatize(token) for token in tokens if token.isalnum() and token not in stopWords]
    return " ".join(tokens)

dataset['preprocessed_review'] = dataset['review'].apply(preprocessing)
dataset

,review,sentiment,preprocessed_review
0,One of the other reviewers has mentioned that ...,1,one reviewer mentioned watching 1 oz episode h...
1,A wonderful little production. <br /><br />The...,1,wonderful little production br br filming tech...
2,I thought this was a wonderful way to spend ti...,1,thought wonderful way spend time hot summer we...
3,Basically there's a family where a little boy ...,0,basically family little boy jake think zombie ...
4,"Petter Mattei's ""Love in the Time of Money"" is...",1,petter mattei love time money visually stunnin...
...,...,...,...
49995,I thought this movie did a down right good job...,1,thought movie right good job creative original...
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",0,bad plot bad dialogue bad acting idiotic direc...
49997,I am a Catholic taught in parochial elementary...,0,catholic taught parochial elementary school nu...
49998,I'm going to have to disagree with the previou...,0,going disagree previous comment side maltin on...
49999,No one expects the Star Trek movies to be high...,0,one expects star trek movie high art fan expec...

# Feature engineering

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features =5000)
tfidf_features = tfidf.fit_transform(dataset['preprocessed_review']).toarray()
f_names = tfidf.get_feature_names_out()
tfidf_dataset = pd.DataFrame(tfidf_features, columns = f_names)


X = tfidf_dataset
y = dataset['sentiment']

In [17]:
dataset

,review,sentiment,preprocessed_review
0,One of the other reviewers has mentioned that ...,1,one reviewer mentioned watching 1 oz episode h...
1,A wonderful little production. <br /><br />The...,1,wonderful little production br br filming tech...
2,I thought this was a wonderful way to spend ti...,1,thought wonderful way spend time hot summer we...
3,Basically there's a family where a little boy ...,0,basically family little boy jake think zombie ...
4,"Petter Mattei's ""Love in the Time of Money"" is...",1,petter mattei love time money visually stunnin...
...,...,...,...
49995,I thought this movie did a down right good job...,1,thought movie right good job creative original...
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",0,bad plot bad dialogue bad acting idiotic direc...
49997,I am a Catholic taught in parochial elementary...,0,catholic taught parochial elementary school nu...
49998,I'm going to have to disagree with the previou...,0,going disagree previous comment side maltin on...
49999,No one expects the Star Trek movies to be high...,0,one expects star trek movie high art fan expec...

#  Model Training

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

model = LogisticRegression(random_state = 42)
model.fit(X_train, y_train)

LogisticRegression(random_state=42)

# Model Evaluation

In [23]:
from sklearn.metrics import classification_report
y_pred = model.predict(X_test)

print("\nClassification report:")
print(classification_report(y_test, y_pred,labels = [0,1],target_names=['negative','positive']))

Classification report:
              precision    recall  f1-score   support

    negative       0.90      0.87      0.88      4961
    positive       0.88      0.90      0.89      5039

    accuracy                           0.89     10000
   macro avg       0.89      0.89      0.89     10000
weighted avg       0.89      0.89      0.89     10000